export interface Checklist{
	HorometrosKilometrajes: any[];
	TiposEquipos: any
	TiposEquipos_Id: number
	archivoFactura: string
	archivoManuales: string
	archivoManualesAliado: string
	asignadoDivision: string
	capacidadAliado: string
	checklist: any
	createdAt: any
	cuentaContable: string
	cuentaContableActivos: string
	deletedAt: any
	descripcion: string
	descripcionAliado: string
	duracionGarantia: string
	duracionGarantiaAliado: string
	equipoAliado: string
	estado: string
	estadoAliado: string
	garantia: string
	garantiaAliado: string
	horometro: number
	horometroAliado: number
	id: number
	inventarioAdicional: string
	kilometraje: number
	manualesAliado: string
	marca: string
	marcaAliado: string
	noEconomico: string
	noFactura: string
	noFacturaAliado: string
	noMotor: string
	noPlacas: string
	noSerie: string
	noSerieAliado: string
	nombreCorto: string
	nombreCortoAliado: string
	nombreLargo: string
	placas: string
	proveedor: string
	proveedorAliado: string
	rendimientoPromedio: string
	rendimientoPromedioAliado: string
	responsableResguardo: string
	tasaDepreciacion: string
	tipoVehiculo: string
	truckCode: string
	updatedAt: any
	valorFactura: number
	valorFacturaAliado: number
}